### ISSUE TITLE
20 MB  feels like too heavy for such an app

### ISSUE THREAD

**Issue by KOLANICH** [X1nto/OpenCord#10]

**Comment by Juby210** [comment]
In app.zip there are 2 apps and it's debug build without proguard, so that means that is not release size. ![Screenshot_20211219-144058_MiXplorer.png](https://user-images.githubusercontent.com/31005896/146677000-a0b05614-f13d-4182-88e0-3cd2a6b5c384.png)

**Comment by X1nto** [comment]
Basically what @Juby210 said, but I think it's worth splitting fosscord and regular versions into separate artifacts (or, even better, making an in-app chooser)

**Comment by X1nto** [comment]
Since the title is now changed to 20MB (indicating a single version of the app), I want to clear up why it weighs that much.

1. The builds from GitHub Actions are debug builds that are not minified by proguard, meaning they can contain unused code from libraries.
2. App bundles the Jetpack Compose runtime for UI (since it's decoupled from OS), which also increases the APK size.

**Comment by KOLANICH** [comment]
>App bundles the Jetpack Compose runtime for UI (since it's decoupled from OS), which also increases the APK size.

Yeah, it is a shame Android packages are not distro-way (deb/rpm/apk (Alpine)) packages.

**Comment by X1nto** [comment]
The APK seen in the 0.0.1 release is about 7MBs big, I think that's a reasonable size for the app.

**Comment by KOLANICH** [comment]
>The APK seen in the 0.0.1 release is about 7MBs big, I think that's a reasonable size for the app.

It is a more reasonable size. Thank you. But if one has his flash full and in a wear amplification regime, he would spare every byte. So, reducing size further never harms.
